
export const MEMBER_TASKS_LIST_REQUEST = 'MEMBER_TASKS_LIST_REQUEST'
export const MEMBER_TASKS_LIST_SUCCESS = 'MEMBER_TASKS_LIST_SUCCESS'
export const MEMBER_TASKS_LIST_FAIL = 'MEMBER_TASKS_LIST_FAIL'

export const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST'
export const MEMBER_LIST_SUCCESS = 'MEMBER_LIST_SUCCESS'
export const MEMBER_LIST_FAIL = 'MEMBER_LIST_FAIL'

export const MEMBER_LOGIN_REQUEST = 'MEMBER_LOGIN_REQUEST'
export const MEMBER_LOGIN_SUCCESS = 'MEMBER_LOGIN_SUCCESS'
export const MEMBER_LOGIN_FAIL = 'MEMBER_LOGIN_FAIL'

export const MEMBER_LOGOUT = 'MEMBER_LOGOUT'


export const MEMBER_REGISTER_REQUEST = 'MEMBER_REGISTER_REQUEST'
export const MEMBER_REGISTER_SUCCESS = 'MEMBER_REGISTER_SUCCESS'
export const MEMBER_REGISTER_FAIL = 'MEMBER_REGISTER_FAIL'

export const MEMBER_DETAILS_REQUEST = 'MEMBER_DETAILS_REQUEST'
export const MEMBER_DETAILS_SUCCESS = 'MEMBER_DETAILS_SUCCESS'
export const MEMBER_DETAILS_FAIL = 'MEMBER_DETAILS_FAIL'
export const MEMBER_DETAILS_RESET = 'MEMBER_DETAILS_RESET'

export const MEMBER_UPDATE_PROFILE_REQUEST = 'MEMBER_UPDATE_PROFILE_REQUEST'
export const MEMBER_UPDATE_PROFILE_SUCCESS = 'MEMBER_UPDATE_PROFILE_SUCCESS'
export const MEMBER_UPDATE_PROFILE_FAIL = 'MEMBER_UPDATE_PROFILE_FAIL'
export const MEMBER_UPDATE_PROFILE_RESET = 'MEMBER_UPDATE_PROFILE_RESET'