export const ORGANIZATION_UPDATE_POSTS_LIST_REQUEST = 'ORGANIZATION_UPDATE_POSTS_LIST_REQUEST'
export const ORGANIZATION_UPDATE_POSTS_LIST_SUCCESS = 'ORGANIZATION_UPDATE_POSTS_LIST_SUCCESS'
export const ORGANIZATION_UPDATE_POSTS_LIST_FAIL = 'ORGANIZATION_UPDATE_POSTS_LIST_FAIL'




export const ORGANIZATION_POSTS_LIST_REQUEST = 'ORGANIZATION_POST_LIST_REQUEST'
export const ORGANIZATION_POSTS_LIST_SUCCESS = 'ORGANIZATION_POST_LIST_SUCCESS'
export const ORGANIZATION_POSTS_LIST_FAIL = 'ORGANIZATION_POSTS_LIST_FAIL'

export const ORGANIZATION_POSTS_CREATE_POST_REQUEST = 'ORGANIZATION_POSTS_CREATE_POST_REQUEST'
export const ORGANIZATION_POSTS_CREATE_POST_SUCCESS = 'ORGANIZATION_POSTS_CREATE_POST_SUCCESS'
export const ORGANIZATION_POSTS_CREATE_POST_FAIL = 'ORGANIZATION_POSTS_CREATE_POST_FAIL'


export const ORGANIZATION_LOGIN_REQUEST = 'ORGANIZATION_LOGIN_REQUEST'
export const ORGANIZATION_LOGIN_SUCCESS = 'ORGANIZATION_LOGIN_SUCCESS'
export const ORGANIZATION_LOGIN_FAIL = 'ORGANIZATION_LOGIN_FAIL'
export const ORGANIZATION_LOGOUT = 'ORGANIZATION_LOGOUT'


export const ORGANIZATION_REGISTER_REQUEST = 'ORGANIZATION_REGISTER_REQUEST'
export const ORGANIZATION_REGISTER_SUCCESS = 'ORGANIZATION_REGISTER_SUCCESS'
export const ORGANIZATION_REGISTER_FAIL = 'ORGANIZATION_REGISTER_FAIL'



export const ORGANIZATION_DETAILS_REQUEST = 'ORGANIZATION_DETAILS_REQUEST'
export const ORGANIZATION_DETAILS_SUCCESS = 'ORGANIZATION_DETAILS_SUCCESS'
export const ORGANIZATION_DETAILS_FAIL = 'ORGANIZATION_DETAILS_FAIL'
export const ORGANIZATION_DETAILS_RESET = 'ORGANIZATION_DETAILS_RESET'

export const ORGANIZATION_UPDATE_PROFILE_REQUEST = 'ORGANIZATION_UPDATE_PROFILE_REQUEST'
export const ORGANIZATION_UPDATE_PROFILE_SUCCESS = 'ORGANIZATION_UPDATE_PROFILE_SUCCESS'
export const ORGANIZATION_UPDATE_PROFILE_FAIL = 'ORGANIZATION_UPDATE_PROFILE_FAIL'
export const ORGANIZATION_UPDATE_PROFILE_RESET = 'ORGANIZATION_UPDATE_PROFILE_RESET'